### ISSUE TITLE
Calling mic.stop() is not working once hotword has been spotted

### ISSUE THREAD

**Issue by pierreclr** [linto-ai/WebVoiceSDK#5]
Hi Damien, 

I'm facing a quite weird issue : 
When calling mic.stop() at a first place everything works as expected that means the following icon disappears. But once 'LinTO' hotword has been spotted calling mic.stop() has no effect. 

<img width="115" alt="Chrome mic on" src="https://user-images.githubusercontent.com/14262431/120474160-29e92780-c3a8-11eb-92d6-8223a06f65a4.png">

So I tried modifying WebvoiceSDK since track we got had an "ended" status : 
```
this.stream.getTracks().forEach((track) => {
  if (track.kind === 'audio' && typeof track.stop === 'function') track.stop()
})
```
But still the mic icon persists. 

Do you got any idea on how to really stop listening the user ? 

Thank you

**Comment by damienlaine** [comment]
Testing this on https://webvoicesdk.netlify.app with an old build of WebVoiceSDK

You have a mic object bound to the window. Calling mic.stop() at any time, even after the hot-word has been triggered successfully stops the microphone acquisition.

Tested this with Chrome. Maybe it's a cross-browser compatibility issue.

You might test it with chrome.
