### ISSUE TITLE
parcelRequire is not defined in Electron build

### ISSUE THREAD

**Issue by viis233** [linto-ai/WebVoiceSDK#6]
when using Electron to build desktop app .
after build in exe its happen
![图片](https://user-images.githubusercontent.com/41282272/135955841-073d76d3-f877-472d-ba53-f10fa9feb673.png)

but  after  serve in browser its fine

how to solve ?

**Comment by damienlaine** [comment]
Hello,

Never tested anything related to Electron. Parcel is the bundler i used to pack-up the lib. Seems related.

As you closed this issue, would you mind give us a hint ?

regards
