### ISSUE TITLE
Dependency update broke the library

### ISSUE THREAD

**Issue by remixer-dec** [linto-ai/WebVoiceSDK#7]
After a fresh build the WASM file doesn't work. A month or two ago everything was working as expected. 
npm install + npm test: 
Errors in firefox: 
```
Module.asm.c.apply is not a function

this.wasmInterface is undefined
```
Errors in chrome:
```
TypeError: ___wasm_call_ctors.apply is not a function

Uncaught TypeError: Cannot read properties of undefined (reading 'HEAPF32')
    at Rnnoise.copyPCMSampleToWasmBuffer
```

Also, is it possible to prevent such issues by either adding a package-lock file or [specifying](https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version) the version?

**Comment by damienlaine** [comment]
fixed
